name: ngax_interview_code
description: NGAX interview project
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.19.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.5.0
  r_dart_library: 0.4.0-nullsafety.0
  nil: ^1.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
  - assets/images/bg_dash_box.png
  - assets/images/bg_dash_box_L.png
  - assets/images/bg_dash_box_S.png
  - assets/images/bg_header.png
  - assets/images/icon_delete.png
  - assets/images/icon_text_editor.png
flr:
  core_version: 3.2.0
  dartfmt_line_length: 80
  assets:
  - assets/images
  - assets/texts
  - assets/video
  fonts: []
